version: "3.9"

services:
  backend:
    build: ./backend
    container_name: lms-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend-admin
    container_name: lms-frontend
    ports:
      - "5173:80"   # Map container’s Nginx port 80 → localhost:5173
    depends_on:
      - backend
